theme: jekyll-theme-hacker
title: Rufyty
description: My hacking journey, articles, and CTF writeups.

# Navigation
nav:
  - title: "Home"
    url: /
  - title: "Whoami"
    url: /whoami/
  - title: "Articles"
    url: /articles/
  - title: "CTFs"
    url: /ctfs/
  - title: "Tools"
    url: /tools/
